export const genres = [
  { id: "1", name: "โรแมนติก", slug: "romantic", icon: "heart" },
  { id: "2", name: "แฟนตาซี", slug: "fantasy", icon: "sparkles" },
  { id: "3", name: "ดราม่า", slug: "drama", icon: "theater" },
  { id: "4", name: "สืบสวน", slug: "mystery", icon: "search" },
  { id: "5", name: "สยองขวัญ", slug: "horror", icon: "skull" },
  { id: "6", name: "วาย", slug: "boys-love", icon: "heart-handshake" },
  { id: "7", name: "ยูริ", slug: "yuri", icon: "flower" },
  { id: "8", name: "Sci-Fi", slug: "sci-fi", icon: "rocket" },
  { id: "9", name: "ชีวิตประจำวัน", slug: "slice-of-life", icon: "sun" },
  { id: "10", name: "จีนโบราณ", slug: "chinese-ancient", icon: "scroll" },
];

export const mockNovels = [
  {
    id: "novel-1",
    title: "แสงจันทร์ที่ปลายฟ้า",
    author: "ดาวเหนือ",
    coverImage: null,
    genre: "โรแมนติก",
    viewCount: 125400,
    chapterCount: 45,
    status: "ONGOING",
    synopsis:
      "เมื่อแสงจันทร์ส่องลงมาบนเส้นทางที่สองดวงใจกำลังเดินค้นหากัน เรื่องราวความรักที่เริ่มต้นจากคืนที่ดวงดาวเรียงตัว",
  },
  {
    id: "novel-2",
    title: "เงาแห่งราชัน",
    author: "นักเขียนพเนจร",
    coverImage: null,
    genre: "แฟนตาซี",
    viewCount: 89200,
    chapterCount: 120,
    status: "COMPLETED",
    synopsis:
      "ในดินแดนที่เวทมนตร์คือสิ่งสูงสุด เงาของราชันผู้ล่วงลับกลับมาอีกครั้งพร้อมคำทำนายที่จะเปลี่ยนโชคชะตาของทุกสรรพสิ่ง",
  },
  {
    id: "novel-3",
    title: "คดีที่ 13 : ฆาตกรไร้เงา",
    author: "สายลับปากกา",
    coverImage: null,
    genre: "สืบสวน",
    viewCount: 67800,
    chapterCount: 30,
    status: "ONGOING",
    synopsis:
      "เมื่อนักสืบอัจฉริยะต้องเผชิญกับคดีที่ไม่มีร่องรอยใดๆ ทิ้งไว้ ฆาตกรไร้เงาจะถูกเปิดโปงได้หรือไม่",
  },
  {
    id: "novel-4",
    title: "หัวใจสีจันทร์",
    author: "แก้วตาดาว",
    coverImage: null,
    genre: "ดราม่า",
    viewCount: 234100,
    chapterCount: 65,
    status: "COMPLETED",
    synopsis:
      "ชีวิตที่เต็มไปด้วยบทเรียน ความรัก ความสูญเสีย และการเริ่มต้นใหม่ของหญิงสาวที่ค้นหาตัวเองท่ามกลางเมืองใหญ่",
  },
  {
    id: "novel-5",
    title: "ดวงดาวกลางสายลม",
    author: "ลมหนาว",
    coverImage: null,
    genre: "โรแมนติก",
    viewCount: 156700,
    chapterCount: 52,
    status: "ONGOING",
    synopsis:
      "เขาเป็นนักดนตรีเร่ร่อน เธอเป็นสถาปนิกสาว เมื่อสองคนที่แตกต่างมาเจอกันในเมืองเล็กๆ ริมทะเล",
  },
  {
    id: "novel-6",
    title: "จิตวิญญาณแห่งป่าลึก",
    author: "เสียงกระซิบ",
    coverImage: null,
    genre: "สยองขวัญ",
    viewCount: 45300,
    chapterCount: 18,
    status: "ONGOING",
    synopsis:
      "กลุ่มนักศึกษาที่เข้าไปสำรวจป่าต้องห้าม ค้นพบสิ่งที่เกินกว่ามนุษย์จะอธิบายได้",
  },
  {
    id: "novel-7",
    title: "รักข้ามกาลเวลา",
    author: "นาฬิกาทราย",
    coverImage: null,
    genre: "แฟนตาซี",
    viewCount: 198500,
    chapterCount: 80,
    status: "COMPLETED",
    synopsis:
      "เมื่อนาฬิกาโบราณพาเขาย้อนกลับไป 100 ปี เขาจะกลับมาได้หรือไม่ หรือจะเลือกอยู่กับรักที่เจอในอดีต",
  },
  {
    id: "novel-8",
    title: "สายรุ้งหลังฝน",
    author: "ดาวเหนือ",
    coverImage: null,
    genre: "วาย",
    viewCount: 312000,
    chapterCount: 42,
    status: "ONGOING",
    synopsis:
      "เมื่อรุ่นพี่เกรดเอพบกับรุ่นน้องเก็บตัว เรื่องราวที่เริ่มจากสายฝนจะนำพาสายรุ้งมาให้ทั้งสองคน",
  },
];

export const mockChapters = [
  {
    id: "ch-1",
    number: 1,
    title: "บทที่ 1: คืนจันทร์เพ็ญ",
    wordCount: 4200,
    coinPrice: 0,
    isFree: true,
    publishedAt: "2025-01-15",
  },
  {
    id: "ch-2",
    number: 2,
    title: "บทที่ 2: สายลมที่พัดพา",
    wordCount: 3800,
    coinPrice: 0,
    isFree: true,
    publishedAt: "2025-01-18",
  },
  {
    id: "ch-3",
    number: 3,
    title: "บทที่ 3: ดวงตาที่คุ้นเคย",
    wordCount: 5100,
    coinPrice: 0,
    isFree: true,
    publishedAt: "2025-01-22",
  },
  {
    id: "ch-4",
    number: 4,
    title: "บทที่ 4: ความลับในแสงเทียน",
    wordCount: 4500,
    coinPrice: 5,
    isFree: false,
    publishedAt: "2025-01-25",
  },
  {
    id: "ch-5",
    number: 5,
    title: "บทที่ 5: ทางแยกแห่งหัวใจ",
    wordCount: 4800,
    coinPrice: 5,
    isFree: false,
    publishedAt: "2025-01-28",
  },
];
